# Generated by Django 4.1.1 on 2022-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_productcategory_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
